package sequences.gui;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sequences.exceptions.CantDecomposeException;
import sequences.exceptions.OutOfBoundsException;
import sequences.printers.Printer;
import sequences.printers.PrinterDummy;
import sequences.printers.PrinterFile;
import sequences.sequence.Fibonacci;
import sequences.sequence.Integers;
import sequences.sequence.Primes;
import sequences.sequence.Sequence;
import sequences.sequence.Squares;

/**
 *
 * @author xenon
 */
public class MainFrame extends javax.swing.JFrame {

    private Printer printer=new PrinterDummy();
    
    class comboItem {

        private Sequence sq;

        public comboItem(Sequence sq) {
            this.sq = sq;
        }

        public String toString() {
            return sq.getName();
        }

        public Sequence getSq() {
            return sq;
        }
    }

    Sequence currentSq;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        lockSequenceChoice(false);

        ArrayList<comboItem> sqList = new ArrayList<>();
        sqList.add(new comboItem(new Integers()));
        sqList.add(new comboItem(new Squares()));
        sqList.add(new comboItem(new Primes()));
        sqList.add(new comboItem(new Fibonacci()));
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(sqList.toArray());
        jComboBoxSeqences.setModel(comboModel);
    }

    private void lockSequenceChoice(boolean lock) {
        //locks
        jComboBoxSeqences.setEnabled(!lock);
        jButtonSelect.setEnabled(!lock);
        //unlocks
        jButtonShow.setEnabled(lock);
        jTextFieldMax.setEnabled(lock);
        jButtonChange.setEnabled(lock);
        jButtonReset.setEnabled(lock);
        jButtonSave.setEnabled(lock);
        jTextFieldDecompose.setEnabled(lock);
        jButtonDecompose.setEnabled(lock);
        jTextFieldSum.setEnabled(lock);
        jButtonSum.setEnabled(lock);
        if (lock) { //we lock the top
            jLabelMax.setText(Integer.toString(currentSq.getMax()));
        } else { //We lock the bottom
            jLabelMax.setText("---");
            jTextFieldMax.setText("");
            currentSq = null;
            jTextFieldDecompose.setText("");
            jTextFieldSum.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSeqences = new javax.swing.JComboBox<>();
        jButtonSelect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMax = new javax.swing.JTextField();
        jButtonChange = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelMax = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonShow = new javax.swing.JButton();
        jTextFieldDecompose = new javax.swing.JTextField();
        jButtonDecompose = new javax.swing.JButton();
        jTextFieldSum = new javax.swing.JTextField();
        jButtonSum = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonQuit = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonCredits = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sequences");

        jPanel1.setBackground(new java.awt.Color(248, 249, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose sequence"));

        jLabel1.setText("Please select a sequence");

        jComboBoxSeqences.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSelect.setText("Select");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jLabel2.setText("Change upper limit");

        jTextFieldMax.setText("jTextField1");

        jButtonChange.setText("Change");
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });

        jLabel3.setText("Upper limit:");

        jLabelMax.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxSeqences, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelect))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonChange)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMax)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSeqences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelect))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChange)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMax))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Utils"));

        jButtonShow.setText("Show elements");
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jTextFieldDecompose.setText("jTextField1");

        jButtonDecompose.setText("Decompose");
        jButtonDecompose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecomposeActionPerformed(evt);
            }
        });

        jTextFieldSum.setText("jTextField2");

        jButtonSum.setText("Sum");
        jButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save to file");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldSum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jTextFieldDecompose, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDecompose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShow)
                    .addComponent(jButtonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDecompose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDecompose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSum))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonQuit.setText("Quit");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonCredits.setText("Credits");
        jButtonCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreditsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButtonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuit)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonCredits))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        lockSequenceChoice(false);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jButtonCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreditsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Developed by MS", "Credits", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonCreditsActionPerformed

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        currentSq = ((comboItem) jComboBoxSeqences.getSelectedItem()).getSq();
        lockSequenceChoice(true);
    }//GEN-LAST:event_jButtonSelectActionPerformed
   
    private Integer readIntFromTextField(JTextField tf){
        String valStr = tf.getText();
        int val;
        try {
            val = Integer.parseInt(valStr);
        } catch (NumberFormatException ex) {
            showError("Wrong value.");
            return null;
        }
        return val;
    }
    
    private void showError(String msg){
        JOptionPane.showMessageDialog(this, msg , "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void showInfo(String msg){
        JOptionPane.showMessageDialog(this, msg , "Info", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        Integer val=readIntFromTextField(jTextFieldMax);
        if (val==null){
            return;
        }
        currentSq.setMax(val);
        jLabelMax.setText(Integer.toString(currentSq.getMax()));
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        // TODO add your handling code here:
        TextArea tArea=new TextArea(this,true);
        tArea.setText(printer.print(currentSq));
        tArea.setVisible(true);
    }//GEN-LAST:event_jButtonShowActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String filename=JOptionPane.showInputDialog(this, "Please input a filename","output/sequences.txt");
        if (filename.isEmpty()) {
            return;
        }
        Printer printerFile=new PrinterFile(filename);
        printerFile.print(currentSq);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumActionPerformed
        Integer val=readIntFromTextField(jTextFieldSum);
        if (val==null){
            return;
        }
        int sum;
        try {
            sum=currentSq.getSum(val);
            showInfo("Suma: "+sum);
        } catch (OutOfBoundsException ex){
            showError(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSumActionPerformed

    private void jButtonDecomposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecomposeActionPerformed
        Integer val=readIntFromTextField(jTextFieldDecompose);
        if (val==null){
            return;
        }
        try {
        ArrayList<Integer> list=currentSq.decompose(val);
        TextArea ta=new TextArea(this, true);
        ta.setText(printer.PrintDecomposition(list));
        ta.setVisible(true);
        } catch (CantDecomposeException ex){
            showError(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDecomposeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChange;
    private javax.swing.JButton jButtonCredits;
    private javax.swing.JButton jButtonDecompose;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JButton jButtonSum;
    private javax.swing.JComboBox<String> jComboBoxSeqences;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldDecompose;
    private javax.swing.JTextField jTextFieldMax;
    private javax.swing.JTextField jTextFieldSum;
    // End of variables declaration//GEN-END:variables
}
